name: ci

on: [push, pull_request]

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run ./ci/fmt.sh
        uses: ./ci/container
        with:
          args: ./ci/fmt.sh

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run ./ci/lint.sh
        uses: ./ci/container
        with:
          args: ./ci/lint.sh

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run ./ci/test.sh
        uses: ./ci/container
        with:
          args: ./ci/test.sh
