name: ci
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  go-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - uses: WillAbides/setup-go-faster@v1.8.0
        with:
          go-version: "1.18.x"

      - uses: dominikh/staticcheck-action@v1.2.0
        with:
          install-go: false
          version: "2022.1"

      - name: Install goimports
        run: go install golang.org/x/tools/cmd/goimports@latest

      - name: install golint
        run: go install golang.org/x/lint/golint@latest
      
      - name: install goasmfmt
        run: go install github.com/klauspost/asmfmt/cmd/asmfmt@latest

      - run: goimports -local github.com/fortytw2/websocket -w .
      - run: golint -set_exit_status ./...
      - run: go mod tidy
      - run: git diff --exit-code

  go-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - uses: WillAbides/setup-go-faster@v1.8.0
        with:
          go-version: "1.18.x"

      - name: vet
        run: go vet -v ./...

      - name: test
        # our tests are not parallel safe
        run: go test -v ./...
